# Generated by Django 4.1.1 on 2022-10-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_livro_isbn_alter_autor_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={"ordering": ["descricao"]},
        ),
    ]
